### PR TITLE
Catch any errors returned by Sentry.

### PR DESCRIPTION
**Pull request by gregholland**
Creating this PR to get the ball rolling on a fix for https://github.com/hautelook/sentry-client/issues/5

How should we go about logging the error?

### CODE REVIEW

**Comment by hjr3** [comment]
Actually, shouldn't you just whitelist the Guzzle exception as an ignored exception?

As for logging, we would have to allow the class to accept a Monolog interface.

**Comment by adrienbrault** [comment]
The error handler should take care of that https://github.com/hautelook/sentry-client/blob/master/src/Hautelook/SentryClient/ErrorHandler.php#L60

**Comment by gregholland** [comment]
@hjr3 - whitelisting the Guzzle exception would stop it cascading into an infinite loop of errors if Sentry continues to return an error, but the fact that that is still possible if you don't do that is not ideal. 

Also, in the my case, Symfony has been throwing deprecation notices, these don't stop anything in my app working, but if for whatever reason Sentry throws back an error my app shouldn't throw an exception because of that.

**Comment by adrienbrault** [comment]
@gregholland https://github.com/hautelook/SentryBundle/blob/master/DependencyInjection/Configuration.php#L42-L45

**Pull request closed without merging**
